ALTER TABLE subscriptiongroup_subscriber ALTER CONSTRAINT sg_s_sg_sgid_fkey DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE subscriptiongroup_subscriber ALTER CONSTRAINT sg_s_s_sid_fkey DEFERRABLE INITIALLY DEFERRED;
